spring:
    jpa:
        show_sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                cache:
                    use_second_level_cache: true
                    region:
                        factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory